version: '2'
services:
    kraken-app:
        image: kraken
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kraken-mysql:3306/kraken?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kraken-mysql:
        extends:
            file: mysql.yml
            service: kraken-mysql
